### ISSUE TITLE
Great work! But find some possible minor issues.

### ISSUE THREAD

**Issue by tingxueronghua** [UCSC-VLAA/HQ-Edit#1]
Great to see such an open-source dataset constructed by DALLE-3. The previous image editing datasets all have lower image qualities and your work contributes a lot to the open-source community. However, I found two minor issues when playing with your huggingface demo. And I am writing to inquire whether you have faced similar ones.

The first one is that the ip2p trained with your dataset seems to perform worse on pictures in the real world. It indeed works well on synthetic images. Have you noticed similar issues? 

The second one is that the model seems to perform worse when the instructions try to edit only specific areas of a given image while keeping the others unchanged.

Here is one example:

The instructions:
change the view for an ocean

The given original image:
![view_tosea](https://github.com/UCSC-VLAA/HQ-Edit/assets/40715314/6d78ebd2-244b-4f75-92c1-aad528a853c8)
The image edited by your model
![edited](https://github.com/UCSC-VLAA/HQ-Edit/assets/40715314/49fab92d-50a6-4f79-b358-db40af809ae0)

The image edited by ip2p trained using MagicBrush:
![image](https://github.com/UCSC-VLAA/HQ-Edit/assets/40715314/e4d7b1e6-accd-45c7-9b7b-62f42bfb3a71)

**Comment by tingxueronghua** [comment]
I have to say it is quite surprising to see the demo working well especially on synthetic images. I am downloading the dataset and looking forward to training a model using it.

**Comment by TheFllood** [comment]
Thanks for using our demo! We found the same issue and are working on it!
