### ISSUE TITLE
'NoneType' object has no attribute 'tokenize'

### ISSUE THREAD

**Issue by Code-kunkun** [UCSC-VLAA/HQ-Edit#2]
<img width="1026" alt="image" src="https://github.com/UCSC-VLAA/HQ-Edit/assets/58265850/6853339b-c488-47b4-8de0-f01aaf015eec">
😭The following error is reported when running the given code. The tokenizer_2 and text_encoder_2 related files seem to be missing from the given checkpoint file.

**Comment by TheFllood** [comment]
Hello, I have updated the Quick Start section in the README with the new code. Please try running it again to see if it works now.
