### ISSUE TITLE
number of images 

### ISSUE THREAD

**Issue by betterze** [UCSC-VLAA/HQ-Edit#3]
Dear HQ-Edit team,

Thank you for sharing this great work. 

You mention that there are 200k edits in the dataset, but I only see 99k edits after I download the dataset

```
from datasets import load_dataset
dataset=load_dataset('UCSC-VLAA/HQ-Edit',num_proc=16)
dataset 
```

the output is 

```
DatasetDict({
    train: Dataset({
        features: ['input', 'input_image', 'edit', 'inverse_edit', 'output', 'output_image'],
        num_rows: 98675
    })
})
```

I try to delete the cache and redownload the dataset, and the number of images stay the same. Did I make any mistake in my command? thx alot 

Best wishes,
Zongze

**Comment by betterze** [comment]
Do you consider the reverse direction to be a different edit? so 99k*2 around 200k?

**Comment by TheFllood** [comment]
Yes, 99kedit + 99kinverse_edit =around 200k.

**Comment by betterze** [comment]
get it, thx
