### ISSUE TITLE
Release of the new metrics (Alignment and Coherence)

### ISSUE THREAD

**Issue by BennoKrojer** [UCSC-VLAA/HQ-Edit#4]
Hello,
First of all really cool work! I am planning on using some of your data and insights in a paper I am working on. For now I was wondering if you could release the metric you used? I.e. a script that has the instruction for GPT-V and how to call it.

Best,
Benno

**Comment by TheFllood** [comment]
Hi, the code for the two metrics has been released. Please feel free to try it out.

**Comment by BennoKrojer** [comment]
Thank you!
