### ISSUE TITLE
Training script and insights

### ISSUE THREAD

**Issue by vinm007** [UCSC-VLAA/HQ-Edit#5]
Hi all,
Thanks for your contribution in dataset and model. Have seen lot of approaches/techniques coming but the quality dataset was missing for this task.
I am planning to conduct some experiments. If possible, Please share the training scripts and some insights about the training setup of SDXL- Infra and any optimization used

Thanks

**Comment by TheFllood** [comment]
Hi, we use the script from huggingface: https://github.com/huggingface/diffusers/blob/main/examples/instruct_pix2pix/train_instruct_pix2pix.py for training.
and for SDXL: https://github.com/huggingface/diffusers/blob/main/examples/instruct_pix2pix/train_instruct_pix2pix_sdxl.py
For the insights and setup you can refer to its readme or the original instructpix2pix paper.
